### ISSUE TITLE
Add Travis integration and badge

### ISSUE THREAD

**Issue by fulldecent** [jennijuju/AionFungibleTokenContractTemplate#6]
Please use the specified test instructions (#5) in a test command using the preferred test suite (npm?, junit?) then add Travis integration so these tests are run with each commit. Then add a badge showing test results to the README.

**Comment by fulldecent** [comment]
This is solved here https://github.com/jennijuju/ATS_CI

But still recommend to add to this repo.

**Comment by jennijuju** [comment]
Added.
